# my global config
global:
  scrape_interval: 1s # By default, scrape targets every 1 second
  evaluation_interval: 1s # By default, scrape targets every 1 second

# remote_write:
#   - url: "http://remote-storage-adapter:9201/write"

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-tendermint0_1"
    static_configs:
      - targets: ["node0_1:26660"]
  
  - job_name: "node-rpc0_1"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["node0_1:6065"]      

  - job_name: "node-tendermint1_1"
    static_configs:
      - targets: ["node1_1:26660"]

  - job_name: "node-rpc1_1"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["node1_1:6065"]

  - job_name: "node-tendermint2_1"
    static_configs:
      - targets: ["node2_1:26660"]

  - job_name: "node-rpc2_1"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["node2_1:6065"]

  - job_name: "node-tendermint3_1"
    static_configs:
      - targets: ["node3_1:26660"]

  - job_name: "node-rpc3_1"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["node3_1:6065"]

  - job_name: "node-tendermint0_2"
    static_configs:
      - targets: ["node0_2:26660"]
  
  - job_name: "node-rpc0_2"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["node0_2:6065"]      

  - job_name: "node-tendermint1_2"
    static_configs:
      - targets: ["node1_2:26660"]

  - job_name: "node-rpc1_2"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["node1_2:6065"]

  - job_name: "node-tendermint2_2"
    static_configs:
      - targets: ["node2_2:26660"]

  - job_name: "node-rpc2_2"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["node2_2:6065"]

  - job_name: "node-tendermint3_2"
    static_configs:
      - targets: ["node3_2:26660"]

  - job_name: "node-rpc3_2"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["node3_2:6065"]            

  - job_name: "tx-bot1"
    static_configs:
      - targets: ["tx-bot1:8080"]

  - job_name: "tx-bot2"
    static_configs:
      - targets: ["tx-bot2:8080"]

