# my global config
global:
  scrape_interval: 1s # By default, scrape targets every 1 second
  evaluation_interval: 1s # By default, scrape targets every 1 second

# remote_write:
#   - url: "http://remote-storage-adapter:9201/write"

scrape_configs:

  - job_name: 'prometheus'
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "single-node-tendermint1"
    static_configs:
      - targets: ["single-node1:26660"]

  - job_name: "single-node-rpc1"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["single-node1:6065"]

  - job_name: "single-node-tendermint2"
    static_configs:
      - targets: ["single-node2:26660"]

  - job_name: "single-node-tendermint-api2"
    params:
      format: ['prometheus']
    static_configs:
      - targets: ["single-node2:1317"]

  - job_name: "single-node-rpc2"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["single-node2:6065"]

  - job_name: "tx-bot1"
    static_configs:
      - targets: ["tx-bot1:8080"]

  - job_name: "tx-bot2"
    static_configs:
      - targets: ["tx-bot2:8080"]

